### ISSUE TITLE
Work on a control panel for managing the TermKit service running on the local computer.

### ISSUE THREAD

**Issue by hach-que** [WindowsTermKit/TermKit#3]
Work on a control panel for managing the TermKit service running on the local computer.

Could we implement this as a Control Panel applet (requires writing a Visual C++ DLL)?

**Comment by hach-que** [comment]
Here's what I'm thinking it might look like:

![A mockup of the control applet.](https://github.com/WindowsTermKit/TermKit/raw/48aa71ec535b40cc4ed750a09df2a6f7dc61fbb0/Mockups/WindowsConfiguration.png)

**Comment by teh-hippo** [comment]
I'd be willing to start investigating that.  I'm not familiar with github
all that much yet, but can we assign issues?

Also, what about not a control panel app, rather just a separate settings
executable?

Michael

**Comment by hach-que** [comment]
> I'd be willing to start investigating that.  I'm not familiar with github all that much yet, but can we assign issues?

I'm not sure whether I'm the only one able to assign issues (GitHub doesn't have an advanced permissions system, so I can either give you guys Pull, Push & Pull or Push, Pull & Administrative Tasks).  It's just under the title of the issue, in this case it'll say "mikesena is assigned" with the settings icon next to it.

> Also, what about not a control panel app, rather just a separate settings executable?

Don't really want to do this; I'd rather have the Windows version of TermKit feel like an integrated component to the system (the other thing we can do along these lines is an MMC snap-in; I don't know which is more difficult).
